# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5b6799ef4b26ef60dc8b7e7df7ea8d6f144013df27572d8f9d1761ee3622f64020c0694e97d7fed5c670242f11742ed1f9325d660632951ea9603daf89b880a

test:
  secret_key_base: 149b164152b2dec62c46cb7b3489de328de93d3b8e7534578f1172c391154f86dbedd3a2804406531b1af19a4f0ee847c1997c3c6a705162d5ba9c2f01e8b6fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
